---
- name: this is my tomcatapp
  hosts: all
  become: yes
  vars:
    java_package_name: openjdk-8-jdk
    tomcat_version: tomcat9
  tasks:
    - name: installing java on my node
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: true
        state: present
    - name: install tomcat
      ansible.builtin.apt:
        name: "{{ tomcat_version }}"
        update_cache: true
        state: present
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp
        state: directory
        mode: '0755'
    - name: Download gameoflife war file
      ansible.builtin.get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
        dest: /tmp
        mode: '0777'
    - name: Create a systemd unit file
      ansible.builtin.copy:
        src: /tmp/gameoflife.war
        dest: /var/lib/tomcat9/webapps/gmaeoflife.war
    