---
- name: this is my tomcatapp
  hosts: all
  become: yes
  vars:
    packages:
      - openjdk-8-jdk
      - tomcat9
    source_location: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
    target_location: /var/lib/tomcat9/webapps/gameoflife.war
    tomcat9_service: tomcat9
  tasks:
    - name: install java-8 & tomcat9
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    - name: download game of life
      ansible.builtin.get_url:
        url: "{{ source_location }}"
        dest: "{{ target_location }}"
      notify:
        - restart tomcat9
  handlers:
    - name: restart tomcat9
      ansible.builtin.service:
        name: "{{ tomcat9_service }}"
        state: restarted